apiVersion: v1
kind: Service
metadata:
  name: kubeserviceappv1
spec:
  selector:
    app: kubeapp
  ports:
    - port: 8080
      targetPort: 4000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedeploy
spec: 
  replicas: 4
  selector:
    matchLabels:
      app: kubeapp
  template:
    metadata:
      labels:
        app: kubeapp
    spec:
      containers:
        - name: kubecontainer
          image: andresaguiarok/aplicativo:1.0.0
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URL
              value: mongodb+srv://andresaguiarok:andres-2408@cluster0.wbacuba.mongodb.net/ecommerceBackend?retryWrites=true&w=majority
          imagePullPolicy: Always